# Generated by Django 4.1.7 on 2024-04-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClient',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_created], verbose_name='created')),
            ],
            options={
                'verbose_name': 'relationship book client',
                'verbose_name_plural': 'relationships book client',
                'db_table': '"library"."book_client"',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(max_length=100, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_created], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=library_app.models.get_datetime, null=True, validators=[library_app.models.check_modified], verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='money')),
                ('full_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('books', models.ManyToManyField(through='library_app.BookClient', to='library_app.book', verbose_name='books')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': '"library"."client"',
            },
        ),
        migrations.AddField(
            model_name='bookclient',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='bookclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.client', verbose_name='client'),
        ),
        migrations.AlterUniqueTogether(
            name='bookclient',
            unique_together={('book', 'client')},
        ),
    ]
