# Generated by Django 4.1.7 on 2024-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_client_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='price'),
        ),
    ]
